config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/hi', to:'welcome#index'
  resources :articles do
    resources :comments
  end
  # The Past Line Equals These 7 Lines
  # get 'articles', to: 'articles#index'
  # get 'articles/new', to: 'articles#new'
  # post 'articles', to: 'articles#create'
  # get 'articles/:id/edit', to: 'articles#edit'
  # put 'articles/:id', to: 'articles#edit'
  # get 'articles/:id', to: 'articles#show'
  # delete 'articles/:id', to: 'articles#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments , dependent: :destroy
    belongs_to :user
    validates :title, presence: true,
        length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles , dependent: :destroy
  has_many :comments , dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    # Signup Additional Field
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  # Article Crud Operations
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    # We've Created this object in Addition To Handle The Error Msg's
    @article = Article.new
  end  
  
  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  # Private Method For Article Validation (DRY Principle)
  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :get_article, only: [:edit, :update, :create, :destroy]
    before_action :get_comment, only: [:edit, :update, :destroy]

    def create
        @comment = @article.comments.create(comment_params)
        @comment.commenter = current_user.email
        @comment.user_id = current_user.id
        @comment.save
        redirect_to article_path(@article)
    end

    def edit
    end

    def update
        if @comment.update(comment_params)
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @comment.destroy
        redirect_to article_path(@article)
    end

    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
    
    def get_article
        @article = Article.find(params[:article_id])
    end

    def get_comment
        @comment = @article.comments.find(params[:id])
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "Error") %> 
        Occured while Saving the Articles
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back to Articles', articles_path %>

app/views/articles/index.html.erb
<div class="container">

  <h1 style="color: tomato;">Listing Articles</h1>
 


<table class="table text-center bg-dark text-light">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Operations</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article), :class => "btn btn-info" %>
      <% if current_user.admin || current_user.id == article.user_id %>
        <%= link_to 'Edit', edit_article_path(article), :class => "btn btn-success" %>
        <%= link_to 'Delete', article_path(article),
              method: :delete, :class => "btn btn-danger" %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>
<br/>
<h2>Hello, <%= current_user.name %> in Addition To Add New Article</h1>
<h2>
<%= link_to 'New article', new_article_path,:class => "btn btn-success" %>
</h2>

</div>

app/views/articles/new.html.erb
<h1>Create Article</h1>

<%= render 'form' %>
<h2>
<%= link_to 'Back To Articles', articles_path %>
</h2>

app/views/articles/show.html.erb
<div class="container col-8" >
    
      
<br>
    <div class="card">
      <h4 class="card-header"><%= @article.title %>
      <% if current_user.admin || current_user.id == @article.user_id %>
        <div style="float:right;">
        <%= link_to 'Edit Article', edit_article_path(@article),:class => "btn btn-success" %>
      </div>
      <% end %>
      
      </h4>
      
      <div class="card-body">
        <p class="card-text"><%= @article.text %>
      </div>
    </div>
    <br>
  <h4 style="color: brown;">Users Comments</h4>
  <br>
  <%= render @article.comments %>

  <h2 style="color: crimson;">Add a comment:</h2>
  <%= render 'comments/form' %>
  <%= link_to 'Back To Articles', articles_path ,:class => "btn btn-info"%>
</div>

app/views/comments/_comment.html.erb
<div>

  <p>
  <strong><%= comment.commenter %></strong>
  
  <div style="float:right;">

    
  <% if current_user.admin || current_user.id == comment.user_id %>
    <%= link_to 'Edit Comment', edit_article_comment_path(comment.article,comment),:class => "btn btn-success" %>
    <%= link_to 'Delete Comment', [comment.article, comment],
            method: :delete,
            data: { confirm: 'Are you sure you want to Delete This Comment?' },:class => "btn btn-danger" %>
    
  <% end %>

  </div>
  
</p>
 
<p>
  <%= comment.body %>
</p>

</div>
--------------------------------------------

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <div class="form-group">
    
    <%= form.text_field :commenter, :value => current_user.name,:disabled => true,class: 'form-control col-5' %>
  </div>
    
    <div class="form-group">
    <%= label_tag :commenter, 'Comment Content' %>
    <%= form.text_area :body, class: 'form-control col-5' %>
    </div>
    <%= form.submit('Add Comment', :class => "btn btn-success")%>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
 
<%= form_with(model: [ @article, @comment], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back to Articles', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beta Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Welcome <%= current_user.name %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
        </div>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active" id="logoutList" >
              
                  <%= link_to 'Logout', destroy_user_session_path, method: :delete ,:class => "btn btn-danger"%>
              
            </li>
        </ul>
    </nav> 
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome <%= current_user.name %></h1>
<h2>
<%= link_to 'Go To Articles', articles_path %>
</h2>